# Generated by Django 3.2.12 on 2022-03-10 08:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity_potential_impact',
            field=models.CharField(blank=True, choices=[('slightly', 'Geringfügig'), ('limited', 'Begrenzt'), ('significant', 'Bedeutend'), ('maximum', 'Maximal')], max_length=255, null=True, verbose_name='Schwere der möglichen Auswirkungen'),
        ),
    ]
