# Generated by Django 3.2.12 on 2022-03-14 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentform', '0002_auto_20220310_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='incident',
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name=''),
            preserve_default=False,
        ),
    ]
